<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html>
  <head>
    <title>ICME 2006</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="stylesheet" type="text/css" href="CommonFiles/icme2006.css">

    <style type="text/css" media="print">
<!--
    #MenuBlock { display: none; }
    #ContentBlock { margin-left: 1em; }
-->
    </style>
  </head>
  <body>
<div id="HeaderBlock"><img src="images/ICME2006-WebHeader.gif" alt="ICME 2006 Toronto"></div>
<div id="columnContainer">
<div id="MenuBlock"><div id="MenuBlock-content">
  <ul id="navigation">
    <li><a href="default.asp">Home</a></li>
    <li><a href="CallForPapers.asp">Call for Papers</a></li>
    <li><a href="ImportantDates.asp">Important Dates</a></li>
    <li><a href="Keynotes.asp">Keynote Talks</a></li>
    <li><a href="Papers.asp">Paper Submission</a></li>
    <li><a href="RegularProgram.asp">Technical Program</a></li>
    <li><a href="Registration.asp">Registration</a></li>
    <li><a href="MeetingSchedule.asp">Meeting Schedule</a></li>
    <li><a href="Housing.asp">Accommodation</a></li>
    <li><a href="SpecialSessions.asp">Special Sessions</a></li>
    <li><a href="Tutorials.asp">Tutorials</a></li>
    <li><a href="SocialEvents.asp">Social Events</a></li>
    <li><a href="Venue.asp">Venue</a></li>
    <li><a href="AboutToronto.asp">About Toronto</a></li>
    <li><a href="TechnicalCommittee.asp">Technical Program Committee</a></li>
    <li><a href="OrganizingCommittee.asp">Organizing Committee</a></li>
    <li><a href="SponsorSupport.asp">Sponsors</a></li>
  </ul>
</div></div>
<div id="ContentBlock"><div id="ContentBlock-content"><!-- End Header -->


<h1>Accepted Papers</h1>

<p>Following is the list of accepted papers for ICME 2006, sorted by paper ID.</p>

<p>
1012: THE HYDRAULOPHONE: INSTRUMENTATION FOR TACTILE FEEDBACK FROM FLUID STREAMS AS A NEW MULTIMEDIA INTERFACE<br>
1014: A NOVEL SCALABLE AUDIO CODING SCHEME FOR DIGITAL AUDIO BROADCAST<br>
1016: A SINGLE HEISENBERG-GABOR BASED FIGURE-OF-MERIT BASED ON THE MODULATION TRANSFER FUNCTION OF DIGITAL IMAGING SYSTEMS<br>
1026: OPTIMAL LINEAR COMBINATION OF DENOISING SCHEMES FOR EFFICIENT REMOVAL OF IMAGE ARTIFACTS<br>
1027: ON THE DETECTION OF MULTIPLICATIVE WATERMARKS IN THE WAVELET AND DCT DOMAINS<br>
1032: THE SEMANTIC PATHFINDER FOR GENERIC NEWS VIDEO INDEXING<br>
1041: IDENTIFY SPORTS VIDEO SHOTS WITH “HAPPY” OR “SAD” EMOTIONS<br>
1045: OPTIMIZED CHAMFER MATCHING FOR SNAKE-BASED IMAGE CONTOUR REPRESENTATIONS<br>
1047: ANALYTICAL MODEL OF ZERO QUANTIZED DCT COEFFICIENTS FOR VIDEO ENCODER OPTIMIZATION<br>
1054: SPATIALLY ADAPTIVE WAVELET THRESHOLDING FOR IMAGE WATERMARKING<br>
1059: EXPLOITING TOPIC THREAD STRUCTURES IN A NEWS VIDEO ARCHIVE FOR THE SEMI-AUTOMATIC GENERATION OF VIDEO SUMMARIES<br>
1062: A DECENTRALIZED KEY MANAGEMENT SCHEME IN OVERLAY MULTICAST NETWORK<br>
1064: ONLINE DOUBLETALK DETECTOR CALIBRATION FOR ACOUSTIC ECHO CANCELLATION IN VIDEOCONFERENCING SYSTEMS<br>
1066: PERFORMANCE ANALYSIS OF SCHEDULING ALGORITHMS FOR BURSTY TRAFFIC IN IEEE 802.15.3 TDMA MECHANISM<br>
1072: CODING ARTIFACT REDUCTION USING NON-REFERENCE BLOCK GRID VISIBILITY MEASURE<br>
1074: DISTRIBUTED STREAMING VIA PACKET PARTITIONING<br>
1077: RECOGNIZING COMMERCIALS IN REAL-TIME USING THREE VISUAL DESCRIPTORS AND A DECISION-TREE <br>
1078: SELF-EMBEDDING DATA HIDING FOR NON-GAUSSIAN STATE-DEPENDENT CHANNELS: LAPLACIAN CASE<br>
1079: EMBEDDED CODING OF THE MOTION-COMPENSATED 3-D WAVELET COEFFICIENTS BY CONCATENATING SPATIAL AND TEMPORAL ORIENTATION TREES <br>
1081: SPEAKER IDENTIFICATION USING A MICROPHONE ARRAY AND A JOINT HMM WITH SPEECH SPECTRUM AND ANGLE OF ARRIVAL<br>
1084: ONLINE TRAINING-ORIENTED VIDEO SHOOTING NAVIGATION SYSTEM BASED ON REAL-TIME CAMERAWORK EVALUATION<br>
1088: CLUSTERING-BASED ANALYSIS OF SEMANTIC CONCEPT MODELS FOR VIDEO SHOTS<br>
1091: EVALUATING RETRIEVAL TECHNIQUES BASED ON PARTIALLY ORDERED GROUND TRUTH LISTS<br>
1092: A TWO-LAYER GRAPHICAL MODEL FOR COMBINED VIDEO SHOT AND SCENE BOUNDARY DETECTION<br>
1093: MULTIMEDIA INDEXING AND FAST RETRIEVAL BASED ON A VOTE SYSTEM<br>
1094: IMPROVED METHODS FOR CORRELATING TRANSFORMS IN MULTIPLE DESCRIPTION CODING SYSTEMS<br>
1095: ENHANCED ARCHITECTURAL SUPPORT FOR VARIABLE-LENGTH DECODING<br>
1098: FAST VIDEO OBJECT SELECTION FOR INTERACTIVE TELEVISION<br>
1106: WHICH THOUSAND WORDS ARE WORTH A PICTURE? EXPERIMENTS ON VIDEO RETRIEVAL USING A THOUSAND CONCEPTS<br>
1107: REAL-TIME VIDEO WATERMARKING BASED ON EXTENDED M-SEQUENCES<br>
1110: GENETIC WATERMARKING BASED ON DCT DOMAIN TECHNIQUES<br>
1113: PROTECTION OF 3D OBJECT VISUAL REPRESENTATIONS<br>
1114: APPLYING SUPERVISED CLASSIFIERS BASED ON NON-NEGATIVE MATRIX FACTORIZATION TO MUSICAL INSTRUMENT CLASSIFICATION<br>
1116: A NEW DEBLOCKING ALGORITHM USING SCALE SPACE EDGE DETECTOR AND ADJUSTED CONTOURLET REPRESENTATION<br>
1118: MOTION ESTIMATION BY QUADTREE PRUNING AND MERGING<br>
1119: ARCHITECTURE ANALYSIS FOR LOW-DELAY VIDEO CODING<br>
1120: SEGMENTATION AND RECOGNITION OF MEETING EVENTS USING A TWO-LAYERED HMM AND A COMBINED MLP-HMM APPROACH<br>
1121: SOCIOMETRY BASED MULTIPARTY AUDIO RECORDINGS SEGMENTATION<br>
1125: SYNTHESIS AND CONTROL OF HIGH RESOLUTION FACIAL EXPRESSIONS FOR VISUAL INTERACTIONS<br>
1132: HUMAN VISION SYSTEM AWARE EXHAUSTIVE BLOCK-MATCHING ALGORITHM<br>
1134: MINIMUM PHONEME ERROR BASED FILTER BANK ANALYSIS FOR SPEECH RECOGNITION<br>
1135: DETECTION OF LSB STEGANOGRAPHY BASED ON IMAGE SMOOTHNESS<br>
1139: EXPERIENTIAL SAMPLING BASED FOREGROUND/BACKGROUND SEGMENTATION FOR VIDEO SURVEILLANCE<br>
1141: A SECRET KEY BASED MULTISCALE FRAGILE WATERMARK IN THE WAVELET DOMAIN<br>
1144: A FLEXIBLE CONTENT-BASED APPROACH TO ADAPTIVE IMAGE COMPRESSION<br>
1146: A GEOMETRICALLY ROBUST WATERMARKING SCHEME BASED ON SELF-RECOGNITION WATERMARK PATTERN<br>
1147: AUTOFRAMING: A RECOMMENDATION SYSTEM FOR DETECTING UNDESIRABLE ELEMENTS AND CROPPING ACCORDINGLY PHOTOS AUTOMATICALLY<br>
1150: AN EFFICIENT CRITERION FOR MODE DECISION IN H.264/AVC<br>
1158: EXTRACTION OF BASEBALL TRAJECTORY AND PHYSICS-BASED VALIDATION FOR SINGLE-VIEW BASEBALL VIDEO SEQUENCES<br>
1159: DISTRIBUTED SVM APPLIED TO IMAGE CLASSIFICATION<br>
1161: A HIGH THROUGHPUT VLSI ARCHITECTURE DESIGN FOR H.264 CONTEXT-BASED ADAPTIVE BINARY ARITHMETIC DECODING WITH LOOK AHEAD PARSING<br>
1163: CONTENT-FREE IMAGE RETRIEVAL USING BAYESIAN PRODUCT RULE<br>
1164: TEMPLATE-BASED SEMI-AUTOMATIC PROFILING OF MULTIMEDIA APPLICATIONS <br>
1168: AUTOMATIC ADDRESSEE IDENTIFICATION BASED ON PARTICIPANTS' HEAD ORIENTATION AND UTTERANCES FOR MULTIPARTY CONVERSATIONS<br>
1171: PREDOMINANT VOCAL PITCH DETECTION IN POLYPHONIC MUSIC<br>
1173: FORMAT-INDEPENDENT MULTIMEDIA STREAMING<br>
1174: CONVERSATION SCENE ANALYSIS WITH DYNAMIC BAYESIAN NETWORK BASED ON VISUAL HEAD TRACKING<br>
1175: AN ADAPTIVE DE-INTERLACING ALGORITHM BASED ON TEXTURE AND MOTION VECTOR ANALYSIS<br>
1179: A NOVEL TWO-STAGE RATE CONTROL SCHEME FOR H.264<br>
1181: SIKAS: A SCALABLE DISTRIBUTED KEY MANAGEMENT SCHEME FOR DYNAMIC COLLABORATIVE GROUPS<br>
1183: PROXY-BASED SNR SCALABLE ERROR TRACKING FOR REAL-TIME VIDEO TRANSMISSION OVER WIRELESS BROADBAND<br>
1184: INTERACTIVE HAPTIC TRANSMISSION FOR REMOTE CONTROL SYSTEMS<br>
1186: MODELING ADAPTIVE MEDIA PROCESSING WORKFLOWS<br>
1189: MEDIA SYNCHRONIZATION METHOD FOR VIDEO HYPERMEDIA APPLICATION BASED ON EXTENDED EVENT MODEL<br>
1191: AN EMBEDDED SUGGESTIVE INTERFACE FOR MAKING HOME VIDEOS<br>
1193: KEY FRAME EXTRACTION IN 3D VIDEO BY RATE-DISTORTION OPTIMIZATION<br>
1194: A DECISION MECHANISM FOR PROCESSING MULTIMODAL SERVICES IN FUTURE GENERATION NETWORK<br>
1198: USING SEMANTIC FEATURES FOR SCENE CLASSIFICATION: HOW GOOD DO THEY NEED TO BE?<br>
1200: METHODS FOR NONE INTRUSIVE DELAY MEASURMENT FOR AUDIO COMMUNICATION OVER PACKET NETWORKS<br>
1201: PACKET LOSS MODELING FOR PERCEPTUALLY OPTIMIZED 3D TRANSMISSION<br>
1203: A ROBUST, ENTROPY-BASED AUDIO-FINGERPRINT<br>
1204: LOCALLY EMBEDDED LINEAR SUBSPACES FOR EFFICIENT VIDEO INDEXING AND RETRIEVAL<br>
1205: REMOTE VOICE ACQUISITION IN MULTIMODAL SURVEILLANCE<br>
1206: CLASSROOM MULTIMEDIA INTEGRATION FOR ADVANCED E-PRESENTATIONS<br>
1221: LOCALLY REFINED COLLISION DETECTION OF LARGE SCALE COMPLEX POLYGONAL MESHES IN DISTRIBUTED VIRTUAL ENVIRONMENTS<br>
1223: MORE: A MOBILE OPEN RICH MEDIA ENVIRONMENT<br>
1225: HIGH PERFORMANCE FRACTIONAL MOTION ESTIMATION AND MODE DECISION FOR H.264/AVC <br>
1228: PROTECTION OF VIDEO LOGO WITH RANDOMIZATION<br>
1229: EXTRACTING STORY UNITS IN SPORTS VIDEO BASED ON UNSUPERVISED VIDEO SCENE CLUSTERING<br>
1232: AUTOMATIC MULTI-PLAYER DETECTION AND TRACKING IN BROADCAST SPORTS VIDEO USING SUPPORT VECTOR MACHINE AND PARTICLE FILTER<br>
1239: VIDEOPOT: INDEXING-BASED DESKTOP VIDEO SEARCH SYSTEM<br>
1243: AUDIOVISUAL ANCHORPERSON DETECTION FOR TOPIC-ORIENTED NAVIGATION IN BROADCAST NEWS<br>
1246: ROBUST WATERMARKING IN THE WIGNER DOMAIN<br>
1247: EMOTION RECOGNITION FROM NOISY SPEECH<br>
1252: MIXED TYPE AUDIO CLASSIFICATION WITH SUPPORT VECTOR MACHINE<br>
1254: VIDEO STABILIZATION PERFORMANCE ASSESSMENT<br>
1256: AN ENCODER-EMBEDDED VIDEO DENOISING FILTER BASED ON THE TEMPORAL LMMSE ESTIMATOR<br>
1257: SPORTS PROGRAM BOUNDARY DETECTION<br>
1259: TRICODES: A BARCODE-LIKE FIDUCIAL DESIGN FOR AUGMENTED REALITY MEDIA<br>
1262: A PORTABLE PHONOCARDIOGRAPHIC FETAL HEART RATE MONITOR<br>
1264: MUSICAL ONSET DETECTION BASED ON ADAPTIVE LINEAR PREDICTION<br>
1266: DEGREE PRE-RESERVED HIERARCHICAL TREE FOR MULTIMEDIA MULTICAST<br>
1272: VIDEO AND AUDIO EDITING FOR MOBILE APPLICATIONS<br>
1276: AN IMPROVED APPROACH TO THE LINE-BASED FACE RECOGNITION<br>
1278: DISPARITY-BASED 3D FACE MODELING USING 3D DEFORMABLE FACIAL MASK FOR 3D FACE RECOGNITION<br>
1279: CONTROLLED COMPLEXITY MAP DECODING OF CABAC ENCODED DATA<br>
1280: A LANGUAGE AND ARCHITECTURE FOR AUTOMATING MULTIMEDIA CONTENT PRODUCTION ON GRID<br>
1282: MODEL AND USAGE OF A CORE MODULE FOR AXMEDIS/MPEG-21 CONTENT MANIPULATION TOOLS <br>
1283: OBJECT RECOGNITION AND RECOVERY BY SKELETON GRAPH MATCHING<br>
1284: A NEW WEAPON AGAINST PIRACY: PATENT PROTECTION AS AN ALTERNATIVE STRATEGY FOR ENFORCEMENT OF DIGITAL RIGHTS<br>
1285: MINIMUM DISTORTION LOOK-UP TABLE BASED DATA HIDING<br>
1288: VIDEO BREAK DETECTION BASED ON SIMILARITY ANALYSIS AND TEMPORAL STATISTICAL CHARACTERISTICS<br>
1293: FINDING A SEMANTIC STRUCTURE INTERACTIVELY IN IMAGE DATABASES<br>
1294: A TEMPO FEATURE VIA MODULATION SPECTRUM ANALYSIS AND ITS APPLICATION TO MUSIC EMOTION CLASSIFICATION <br>
1297: AN EVENT-DRIVEN SPORTS VIDEO ADAPTATION FOR THE MPEG-21 DIA FRAMEWORK<br>
1303: ON TRAINING NEURAL NETWORK ALGORITHMS FOR ODOR IDENTIFICATION FOR FUTURE MULTIMEDIA COMMUNICATION SYSTEMS<br>
1304: COST-EFFECTIVE FRAME-LAYER H.264 RATE CONTROL FOR LOW BIT RATE VIDEO<br>
1309: ROBUST TRANSMISSION OF H.264/AVC VIDEO USING ADAPTIVE SLICE GROUPING AND UNEQUAL ERROR PROTECTION<br>
1311: A PATTERN-SEARCH METHOD FOR H.264/AVC CAVLC DECODING<br>
1314: AN OPTIMIZED MAPPING ALGORITHM FOR CLASSIFIED VIDEO TRANSMISSION WITH THE H.264 FLEXIBLE MACROBLOCK ORDERING<br>
1316: RESTORATION OF MOTION BLURRED IMAGES<br>
1317: SEMANTIC SEGMENTATION OF DOCUMENTARY VIDEO USING MUSIC BREAKS<br>
1319: MULTISCALE EDGE-BASED TEXT EXTRACTION FROM COMPLEX IMAGES<br>
1321: AUTOMATIC QUERY EXPANSION IN NEWS VIDEO RETRIEVAL<br>
1326: SECURED MPEG-21 DIGITAL ITEM ADAPTATION FOR H.264 VIDEO<br>
1329: A PIXEL-BASED ROBUST IMAGE WATERMARKING SYSTEM<br>
1337: A NOVEL INTERFACE FOR AUDIO SEARCH<br>
1344: CONTRAST ENHANCEMENT IN DIRECT-PROJECTED AUGMENTED REALITY<br>
1351: DESIGN AND IMPLEMENTATION OF A MULTIMEDIA PERSONALIZED SERVICE OVER LARGE SCALE NETWORKS<br>
1353: WEB BASED CHINESE CALLIGRAPHY LEARNING WITH 3-D VISUALIZATION METHOD<br>
1364: APPROXIMATED CORRELATION MATRIX AND PULSE PREDICTION FOR FAST ALGEBRAIC CODE-EXCITED LPC SPEECH CODERS<br>
1367: AUTOMATIC CLASSIFICATION OF FIELD OF VIEW IN VIDEO<br>
1368: A NONNEGATIVE MATRIX FACTORIZATION SCHEME FOR DIGITAL IMAGE WATERMARKING<br>
1369: WEBDOVE: A WEB-BASED COLLABORATION SYSTEM FOR PHYSICAL TASKS<br>
1371: ADVANCING CONTENT-BASED RETRIEVAL EFFECTIVENESS WITH CLUSTER-TEMPORAL BROWSING IN MULTILINGUAL VIDEO DATABASES <br>
1378: AN IMAGE PROCESSING PIPELINE WITH DIGITAL COMPENSATION OF LOW COST OPTICS FOR MOBILE TELEPHONY<br>
1379: UNEQUAL ERROR PROTECTION FOR VIDEO STREAMING OVER WIRELESS LANS USING CONTENT-AWARE PACKET RETRY LIMIT<br>
1382: DETECTING CHANGES IN USER-CENTERED MUSIC QUERY STREAMS<br>
1386: PREDICTIVE DYNAMIC USER INTERFACES FOR INTERACTIVE VISUAL SEARCH PART I<br>
1389: PING: A GROUP-TO-INDIVIDUAL DISTRIBUTED MEETING SYSTEM<br>
1393: TV COMMERCIAL CLASSIFICATION BY CATEGORIES OF ADVERTISED PRODUCTS OR SERVICES IN VIDEO STREAMS<br>
1394: SOCCER HIGHLIGHT DETECTION USING TWO-DEPENDENCE BAYESIAN NETWORK<br>
1395: REUSE OF MOTION PROCESSING FOR CAMERA STABILIZATION AND VIDEO CODING<br>
1399: DISCRETE POLYNOMIAL TRANSFORM FOR DIGITAL IMAGE WATERMARKING APPLICATION<br>
1401: DMB(DIGITAL MULTIMEDIA BROADCASTING) VOICE EPG APPLICATION<br>
1403: VIDEO BASED PERSON AUTHENTICATION VIA AUDIO/VISUAL ASSOCIATION<br>
1405: TOWARDS AN EFFICIENT INTEGRATION, STRUCTURE AND EXPLORATION OF LANDSCAPE ARCHITECTURE PROJECT INFORMATION<br>
1406: A THREE-LAYER VIRTUAL DIRECTOR MODEL FOR SUPPORTING AUTOMATED MULTI-SITE DISTRIBUTED EDUCATION<br>
1408: SIMILAR SEGMENT DETECTION FOR MUSIC STRUCTURE ANALYSIS VIA VITERBI ALGORITHM<br>
1409: EVALUATION OF PRACTICAL SCALABILITY OF OVERLAY NETWORKS IN PROVIDING VIDEO-ON-DEMAND SERVICE<br>
1410: TOWARDS AUTOMATIC MOBILE BLOGGING<br>
1412: AUTOMATIC CONTENT PLACEMENT IN SPORTS HIGHLIGHTS<br>
1414: A COLLECTION-ORIENTED METADATA FRAMEWORK FOR DIGITAL IMAGES<br>
1415: VIDEO ENCODING AND SPLICING FOR TUNE-IN TIME REDUCTION IN IP DATACASTING (IPDC) OVER DVB-H<br>
1417: SCALABLE RATE-DISTORTION-COMPUTATION HARDWARE ACCELERATOR FOR MCTF AND ME<br>
1418: MEDIA STREAMING WITH CONSERVATIVE DELAY ON VARIABLE RATE CHANNELS<br>
1419: ON THE SECURITY OF MULTIMEDIA ENCRYPTION SCHEMES BASED ON MULTIPLE HUFFMAN TABLE (MHT)<br>
1420: SELECTING KERNEL EIGENFACES FOR FACE RECOGNITION WITH ONE TRAINING SAMPLE PER SUBJECT<br>
1421: COARSE-TO-FINE PEDESTRIAN LOCALIZATION AND SILHOUETTE EXTRACTION FOR THE GAIT CHALLENGE DATA SETS<br>
1423: EFFICIENT OBJECT TRACKING USING CONTROL-BASED OBSERVER DESIGN<br>
1424: A SNAKE-BASED SEGMENTATION ALGORITHM FOR OBJECTS WITH BOUDNARY CONCAVITIES<br>
1431: A BLOCK-MATCHING BASED INTRA FRAME PREDICTION FOR H.264/AVC<br>
1433: A FAST MATCHING PURSUITS ALGORITHM USING SUB-BAND DECOMPOSITION OF VIDEO SIGNALS<br>
1434: RELATIVE DEPTH LAYER GENERATION FOR SINGLE VIDEO BY USE OF MULTIDIMENSIONAL FILTER<br>
1435: A PROTECTION PROCESSOR FOR MPEG-21 PLAYERS<br>
1436: ADAPTIVELY SWITCHING BETWEEN DIRECTIONAL INTERPOLATION AND REGION MATCHING FOR SPATIAL ERROR CONCEALMENT BASED ON DCT COEFFICIENTS<br>
1438: LOSSLESS VISIBLE WATERMARKING<br>
1439: COMPLEXITY ANALYSIS OF H.264 DECODER FOR FPGA DESIGN<br>
1440: APPROXIMATING OPTIMAL VISUAL SENSOR PLACEMENT<br>
1442: DETECTION OF VARIANT WIPE EFFECTS<br>
1443: FUZZY SPATIAL RANKS FOR OBJECT RECOGNITION ACROSS ILLUMINATION CHANGES<br>
1446: PEOPLE IDENTIFICATION WITH LIMITED LABELS IN PRIVACY-PROTECTED VIDEO<br>
1447: ENTROPY AND MEMORY CONSTRAINED VECTOR QUANTIZATION WITH SEPARABILITY BASED FEATURE SELECTION<br>
1448: COUNTING OF VIDEO CLIP REPETITIONS USING A MODIFIED BMH ALGORITHM: PRELIMINARY RESULTS<br>
1449: RATE-DISTROTION OPTIMIZED VIDEO STREAMING FOR SCALABLE H.264<br>
1452: LARGE-SCALE DUPLICATE DETECTION FOR WEB IMAGE SEARCH<br>
1454: AUTOMATIC CLASSIFICATION OF PHOTOGRAPHS AND GRAPHICS<br>
1455: FULLY AND SEMI-AUTOMATIC MUSIC SPORTS VIDEO COMPOSITION<br>
1457: COMPLEXITY SCALABLE 2:1 RESOLUTION DOWNSCALING MPEG-2 TO WMV TRANSCODER WITH ADAPTIVE ERROR COMPENSATION<br>
1458: COMPLEXITY-DISTORTION OPTIMIZED MOTION ESTIMATION ALGORITHM WITH FINE-GRANULAR SCALABLE COMPLEXITY<br>
1459: WAVELET-FUZZY-STOCHASTIC KALMAN FILTERING FOR IMAGE COMPRESSION<br>
1460: A NEW ORIENTED ADAPTIVE CROSS SEARCH ALGORITHM FOR BLOCK MATCHING MOTION ESTIMATION<br>
1461: PERFORMANCE ANALYSIS OF COMPRESSED-DOMAIN AUTOMATIC SPEAKER RECOGNITION AS A FUNCTION OF SPEECH CODING TECHNIQUE AND BIT RATE<br>
1462: A MULTIMEDIA SYSTEM FOR ROUTE SHARING AND VIDEO-BASED NAVIGATION<br>
1464: IMAGE AUTO-ANNOTATION USING A STATISTICAL MODEL WITH SALIENT REGIONS<br>
1465: GEODEC: ENABLING GEOSPATIAL DECISION MAKING<br>
1469: ENHANCED SEMI-SUPERVISED LEARNING FOR AUTOMATIC VIDEO ANNOTATION<br>
1471: MINING RELATIONSHIP BETWEEN VIDEO CONCEPTS USING PROBABILISTIC GRAPHICAL MODELS<br>
1474: A NOVEL MODEL-BASED SEGMENTATION APPROACH TO EXTRACT CAPTION CONTENTS ON SPORTS VIDEOS<br>
1477: ADAPTIVE DUAL AK-D TREE SEARCH ALGORITHM FOR ICP REGISTRATION APPLICATIONS<br>
1478: ENERGY-AWARE MULTI-SOURCE VIDEO STREAMING<br>
1479: AUTOMATIC SEMANTIC ANNOTATION OF IMAGES USING SPATIAL HIDDEN MARKOV MODEL<br>
1481: DIRECTIONAL WEIGHTING-BASED DEMOSAICKING ALGORITHM FOR NOISY CFA ENVIRONMENTS<br>
1484: HIGHLIGHT SUMMARIZATION IN SPORTS VIDEO BASED ON REPLAY DETECTION<br>
1485: INFORMATION EXTRACTION FROM NEWS VIDEO USING GLOBAL RULE INDUCTION TECHNIQUE<br>
1490: REAL-TIME VIDEO INTELLIGENT SURVEILLANCE SYSTEM<br>
1491: A NOVEL DISTRIBUTED INCENTIVE MECHNAISM FOR PEER TO PEER LIVE VIDEO STREAMING<br>
1494: 3D VIDEO AND FREE VIEWPOINT VIDEO – TECHNOLOGIES, APPLICATIONS AND MPEG STANDARDS<br>
1496: ROBUST RIGID MOTION ESTIMATION BASED ON DIFFERENTIAL EVOLUTION<br>
1499: A NOVEL DATA-PARALLEL COPROCESSOR FOR MULTIMEDIA SIGNAL PROCESSING<br>
1501: LIGHTWEIGHT JPEG2000 ENCRYPTION WITH ANISOTROPIC WAVELET PACKETS<br>
1502: WHERE AM I? SCENE RECOGNITION FOR MOBILE ROBOTS USING AUDIO FEATURES<br>
1503: STREAMING OF SCALABLE VIDEO FROM MULTIPLE SERVERS USING RATELESS CODES<br>
1506: IMAGE RETRIEVAL BASED ON USER-SPECIFIED FEATURES IN QUERIES WITH MULTIPLE EXAMPLES<br>
1507: EFFICIENT HAND GESTURE RENDERING AND IDENTIFICATION USING A SIMPLE GESTURE LIBRARY<br>
1508: EFFICIENT ALGORITHM FOR GLOBALLY OPTIMAL UNEVEN ERASURE-PROTECTED PACKETIZATION OF SCALABLE CODESTREAMS<br>
1509: SAMPLING STRATEGIES FOR ACTIVE LEARNING IN PERSONAL PHOTO RETRIEVAL<br>
1510: EVOLUTIONARY FEATURE GENERATION IN SPEECH EMOTION RECOGNITION<br>
1511: PERFORMANCE OF OPTICAL FLOWTECHNIQUES ON GRAPHICS HARDWARE<br>
1513: WATERMARK SYNCHRONIZATION FOR FEATURE-BASED EMBEDDING: APPLICATION TO SPEECH<br>
1514: COST-EFFECTIVE SHARPENING OF SINGLE-SENSOR CAMERA IMAGES<br>
1515: DEMOSAICKING USING VECTOR SPECTRAL MODEL<br>
1517: PERCEPTUAL QUALITY METRIC FOR H.264 LOW BIT RATE VIDEOS<br>
1519: A CONTEXT-AWARE APPROACH FOR MULTIMEDIA PERFORMANCE OPTIMIZATION USING NEURAL NETWORKS IN WIRELESS LAN ENVIRONMENTS<br>
1520: REGION-BASED IMAGE RETRIEVAL USING RADIAL BASIS FUNCTION NETWORK <br>
1523: REGION ENHANCED SCALE-INVARIANT SALIENCY DETECTION<br>
1529: PERFORMANCE-COMPLEXITY ANALYSIS OF HIGH RESOLUTION VIDEO ENCODER AND ITS MEMORY ORGANIZATION FOR DSP IMPLEMENTATION<br>
1531: INTERACTIVE MULTI-VIEW VISUAL CONTENTS AUTHORING SYSTEM<br>
1533: OPTIMIZED RATE ALLOCATION FOR UNBALANCED MULTIPLE DESCRIPTION VIDEO CODING OVER UNRELIABLE PACKET NETWORK<br>
1536: CONSTANT QUALITY AIMED BIT ALLOCATION FOR 3D WAVELET BASED VIDEO CODING<br>
1538: REMOTE CONTROL OF A NETWORKED MOBILE ROBOT USING AN IMMERSIVE LOCOMOTION INTERFACE <br>
1541: MODELING INTERACTIONS FROM EMAIL COMMUNICATION<br>
1542: A NOVEL REVERSE FRAME SELECTION SCHEME FOR VIDEO STREAMING OVER VBR CHANNELS<br>
1543: BLOCK-BASED LOSSLESS DATA HIDING IN DELTA DOMAIN<br>
1544: MOTION ESTIMATION FOR H.264/AVC USING PROGRAMMABLE GRAPHICS HARDWARE<br>
1545: PACKET SCHEDULING OF STREAMING VIDEO WITH FLEXIBLE REFERENCE FRAME USING DYNAMIC PROGRAMMING AND INTEGER ROUNDING<br>
1546: MULTI-RATE, DYNAMIC AND COMPLIANT REGION OF INTEREST CODING FOR JPEG2000<br>
1547: HIERARCHICAL LOAD TESTING ARCHITECTURE USING LARGE SCALE VIRTUAL CLIENTS<br>
1548: SHOT AND SCORING EVENTS IDENTIFICATION OF BASKETBALL VIDEOS<br>
1549: CLASSIFIER OPTIMIZATION FOR MULTIMEDIA SEMANTIC CONCEPT DETECTION<br>
1550: VIDEO WATERMARKING BASED ON NEURAL NETWORKS<br>
1551: HIERARCHICAL SUMMARIZATION OF VIDEOS BY TREE-STRUCTURED VECTOR QUANTIZATION<br>
1559: FAST MULTI-REFERENCE FRAME MOTION ESTIMATION VIA DOWNHILL SIMPLEX SEARCH<br>
1560: ERROR RESILIENT MULTIPLE DESCRIPTION COMPRESSION OF VECTOR GRAPHICS<br>
1565: OPTIMIZATION OF MATCHING PURSUIT ENCODER BASED ON ANALYTICAL APPROXIMATION OF MATCHING PURSUIT DISTORTION<br>
1566: VIDEO OBJECT SEGMENTATION BASED ON OBJECT ENHANCEMENT AND REGION MERGING<br>
1567: IMPROVING SPEAKER DIARIZATION BY CROSS EM REFINEMENT<br>
1572: COMPUTATIONAL INTELLIGENCE TECHNIQUES AND THEIR APPLICATIONS IN CONTENT-BASED IMAGE RETRIEVAL<br>
1574: NOVEL PROGRESSIVE REGION OF INTEREST IMAGE CODING BASED ON MATCHING PURSUITS<br>
1575: FAST PROGRESSIVE MODEL REFINEMENT GLOBAL MOTION ESTIMATION ALGORITHM WITH PREDICTION<br>
1576: ACOUSTIC ECHO CANCELATION FOR HIGH NOISE ENVIRONMENTS<br>
1577: GENERATING A TIME SHRUNK LECTURE VIDEO BY EVENT DETECTION<br>
1584: EXTRACTION OF OUTCROP POINTS FROM VISUAL HULLS FOR MOTION ESTIMATION<br>
1586: SOUND SOURCE SEPARATION OF TRIO USING STEREO MUSIC SOUND SIGNAL BASED ON INDEPENDENT COMPONENT ANALYSIS<br>
1590: MODELING BLOCKING VISUAL SENSITIVITY PROFILE<br>
1591: TWO-LAYER IMAGE RESIZING FOR SCALABLE CODEC<br>
1599: DETECTION AND REMOVAL OF LONG SCRATCH LINES IN AGED FILMS<br>
1603: EVALUATION OF SELF-EDITING BASED ON BEHAVIORS-FOR-ATTENTION FOR DESKTOP MANIPULATION VIDEOS<br>
1607: REMOVING SHADOWS USING FLASH/NOFLASH IMAGE EDGES<br>
1608: USABILITY EVALUATION FOR IMAGE RETRIEVAL BEYOND DESKTOP APPLICATIONS<br>
1612: POWER-AWARE PARTICLE FILTERING FOR VIDEO TRACKING<br>
1613: LEARNING-BASED INTERACTIVE VIDEO RETRIEVAL SYSTEM<br>
1615: IMAGE SEGMENTATION USING PARALLEL SELF ORGANIZING TREE MAP<br>
1616: ACOUSTICALLY-DRIVEN TALKING FACE SYNTHESIS USING DYNAMIC BAYESIAN NETWORKS<br>
1617: MUSIC SIGNAL SYNTHESIS USING SINUSOID MODELS AND SLIDING-WINDOW ESPRIT<br>
1624: A COMBINED BAYESSHRINK WAVELET-RIDGELET TECHNIQUE FOR IMAGE DENOISING<br>
1628: PERCEPTUALLY-ADAPTIVE MOTION COMPENSATED TEMPORAL FILTERING<br>
1629: MOTION ALIGNED SPATIAL SCALABLE VIDEO CODING<br>
1630: TENSOR-BASED MULTIPLE OBJECT TRAJECTORY INDEXING AND RETRIEVAL<br>
1631: DECENTRALIZED MULTIPLE CAMERA MULTIPLE OBJECT TRACKING<br>
1633: GPU ACCELERATED INVERSE PHOTON MAPPING FOR REAL-TIME SURFACE REFLECTANCE MODELING<br>
1637: ON-DEMAND PARTIAL SCHEMA DELIVERY FOR MULTIMEDIA METADATA<br>
1641: SPEECH MODELING WITH MAGNITUDE-NORMALIZED COMPLEX SPECTRA AND ITS APPLICATION TO MULTISENSORY SPEECH ENHANCEMENT<br>
1642: DETECTING MUSICAL SOUNDS IN BROADCAST AUDIO BASED ON PITCH TUNING ANALYSIS<br>
1647: MOTION SEGMENTATION OF 3D VIDEO USING MODIFIED SHAPE DISTRIBUTION<br>
1649: EFFICIENT COMPRESSION OF MULTI-VIEW VIDEO EXPLOITING INTER-VIEW DEPENDENCIES BASED ON H.264/MPEG4-AVC<br>
1651: CMUSEUM: A LOCATION-AWARE WIRELESS VIDEO STREAMING SYSTEM<br>
1652: A BINAURAL DISPLAY FOR RENDERING MULTIPLE SOUND SOURCES BASED ON SPATIAL FEATURES OF HEAD-RELATED TRANSFER FUNCTIONS<br>
1653: DETECTING HUMAN ACTION IN ACTIVE VIDEO<br>
1654: A ROBUST METHOD FOR HIDING VIDEO IN VIDEO<br>
1657: AN EFFICIENT LOCAL CLUSTERING APPROACH FOR SIMPLIFICATION OF 3D POINT-BASED COMPUTER GRAPHICS MODELS<br>
1658: UTILIZING SIGNAL TO SILENCE RATIO INDICATIONS FOR IMPROVED VIDEO COMMUNICATION IN PRESENCE OF 802.11B RESIDUE ERRORS<br>
1659: GPCD:GRID-BASED PREDICTIVE COLLISION DETECTION FOR LARGE-SCALE ENVIRONMENTS IN COMPUTER GAMES<br>
1660: FEMA: A FAST EXPECTATION MAXIMIZATION ALGORITHM BASED ON GRID AND PCA<br>
1663: REAL-TIME DEPTH IMAGE BASED RENDERING HARDWARE ACCELERATOR FOR ADVANCED THREE DIMENSIONAL TELEVISION SYSTEM<br>
1665: WHERE WAS THE PICTURE TAKEN: IMAGE LOCALIZATION IN ROUTE PANORAMAS USING EPIPOLAR GEOMETRY<br>
1667: PROBABILISTIC MULTIMODALITY FUSION FOR EVENT BASED HOME PHOTO CLUSTERING<br>
1669: STATISTICAL TIMING BEHAVIOR ANALYSIS AND REDUCED-COMPLEXITY LINEAR PREDICTION FOR MULTIMEDIA PROCESSING SYSTEMS<br>
1670: FACE SEGMENTATION UNDER UNCONSTRAINED SCENES<br>
1671: MULTIMEDIA INFORMAL COMMUNICATION BY WEARABLE COMPUTER BASED ON REAL-WORLD CONTEXT AND GRAFFITI <br>
1677: ASYMPTOTICALLY OPTIMAL SCALAR QUANTIZERS FOR QIM WATERMARK DETECTION<br>
1682: BIT-STREAM SWITCHING IN MULTIPLE BIT-RATE VIDEO STREAMING USING WYNER-ZIV CODING<br>
1683: SCALABILITY IN HUMAN SHAPE ANALYSIS<br>
1684: A CONDITION-BASED INTRA PREDICTION ALGORITHM FOR H.264/AVC<br>
1687: WAVELET-BASED COLOR IMAGE WATERMARKING USING ADAPTIVE ENTROPY CASTING<br>
1688: DYNAMIC VIEW-DEPENDENT MULTIRESOLUTION TERRAIN VISUALIZATION<br>
1689: COMBINED GESTURE-SPEECH ANALYSIS AND SPEECH DRIVEN GESTURE SYNTHESIS<br>
1692: CONSISTENT GOAL-DIRECTED USER MODEL FOR REALISITC MAN-MACHINE TASK-ORIENTED SPOKEN DIALOGUE SIMULATION<br>
1700: IMPROVING THE PERFORMANCE OF TCP WIRELESS VIDEO STREAMING WITH A NOVEL PLAYBACK ADAPTATION ALGORITHM<br>
1701: USING RATE-DISTORTION METRICS FOR REAL-TIME INTERNET VIDEO STREAMING WITH TCP<br>
1703: AN EFFICIENT REFERENCE FRAME STORAGE SCHEME FOR H.264 HDTV DECODER<br>
1706: IMPROVED GRAPHICAL MODEL FOR AUDIOVISUAL OBJECT TRACKING<br>
1709: COLOR DATA CODING FOR THREE-DIMENSIONAL MESH MODELS CONSIDERING CONNECTIVITY AND GEOMETRY INFORMATION<br>
1710: A PEER-TO-PEER OVERLAY NETWORK FOR REAL TIME VIDEO COMMUNICATION USING MULTIPLE PATHS<br>
1711: A NOVEL RESYNCHRONIZATION METHOD FOR SCALABLE VIDEO OVER WIRELESS CHANNEL <br>
1716: MULTI-VIEW VIDEO CODING USING VIEW INTERPOLATION AND REFERENCE PICTURE SELECTION<br>
1717: CAPTURING-RESISTANT AUDIO WATERMARKING BASED ON DISCRETE WAVELET TRANSFORM<br>
1718: FACE RECOGNITION USING ENERGY PROBABILITY IN DCT DOMAIN<br>
1721: LOW-COMPLEXITY ADAPTIVE BLOCK-SIZE TRANSFORM BASED ON EXTENDED TRANSFORMS<br>
1722: BLOCK-BASED FAST COMPRESSION FOR COMPOUND IMAGES<br>
1729: 3D MODEL SEARCH BASED ON STOCHASTIC ARG MATCHING<br>
1730: ERMDCLIME: ENABLING REAL-TIME MULTIMEDIA DISCUSSION FOR COLLABORATIVE LEARNING IN MOBILE ENVIRONMENT <br>
1731: A NEURAL NETWORK BASED ADAPTIVE ALGORITHM FOR MULTIMEDIA QUALITY FAIRNESS IN WLAN ENVIRONMENTS<br>
1732: JOINT SOURCE-CHANNEL DECODING OF MULTIPLE DESCRIPTION QUANTIZED AND VARIABLE LENGTH CODED MARKOV SEQUENCES<br>
1734: AN EDGE-BASED MEDIAN FILTERING ALGORITHM WITH CONSIDERATION OF MOTION VECTOR RELIABILITY FOR ADAPTIVE VIDEO DEINTERLACING<br>
1736: IMPROVED SIMILARITY-BASED ONLINE FEATURE SELECTION IN REGION-BASED IMAGE RETRIEVAL <br>
1738: ROBUST SPEAKER RECOGNITION USING SNR-AWARE SUBSPACE-BASED ENHANCEMENT AND PROBABILISTIC SVMS<br>
1739: HUMAN OBJECT TRACKING ALGORITHM WITH HUMAN COLOR STRUCTURE DESCRIPTOR FOR VIDEO SURVEILLANCE SYSTEMS<br>
1742: MODELING AND PERFORMANCE ANALYSIS OF INITIAL CONNECTION IN IEEE 802.16 PMP NETWORKS<br>
1745: MOBILITY MANAGEMENT FOR UNTETHERED IMMERSIVE COMMUNICATIONS<br>
1746: MINING TEXT AND VISUAL LINKS TO BROWSE TV PROGRAMS IN A WEB-LIKE WAY<br>
1748: PREDICTION-BASED GESTURE DETECTION IN LECTURE VIDEOS BY COMBINING VISUAL, SPEECH AND ELECTRONIC SLIDES<br>
1749: ADAPTIVE VIDEO NEWS STORY TRACKING BASED ON EARTH MOVER'S DISTANCE<br>
1750: IMAGE CONTENT CLUSTERING AND SUMMARIZATION FOR PHOTO COLLECTIONS<br>
1751: TRACKING OF HUMAN BODY JOINTS USING ANTHROPOMETRY<br>
1753: SUBJECTIVE EVALUATIONS OF AN EXPERIMENTAL GESTUREPHONE<br>
1754: AUTHENTICATING MULTIMEDIA TRANSMITTED OVER WIRELESS NETWORKS: A CONTENT-AWARE STREAM-LEVEL APPROACH<br>
1755: RECOGNIZING FACES IN RECORDED MEETINGS VIA MRC-BOOSTING<br>
1756: NONLINEARLY-ADAPTED LAPPED TRANSFORMS FOR INTRA-FRAME CODING<br>
1757: A 3D SPATIO-TEMPORAL MOTION ESTIMATION ALGORITHM FOR VIDEO CODING<br>
1758: FAST INTER MODE DECISION BASED ON HIERARCHICAL HOMOGENEOUS DETECTION AND COST ANALYSIS FOR H.264/AVC CODERS<br>
1760: CONSTRUCTING ROBUST AND RESILIENT FRAMEWORK FOR COOPERATIVE VIDEO STREAMING<br>
1764: UNEQUAL ITERATIVE DECODING FOR EFFICIENT VIDEO TRANSMISSION<br>
1768: REAL-TIME ITERATIVE SPECTRUM INVERSION WITH LOOK-AHEAD<br>
1770: RESP: SHORTEST-PATH-BASED CACHE REPLACEMENT IN A TRANSCODING PROXY<br>
1771: EVENT-IMPORTANCE BASED CUSTOMIZED AND AUTOMATIC CRICKET HIGHLIGHT GENERATION<br>
1777: RESTORATION OF HALFTONED COLOR-QUANTIZED IMAGES USING LINEAR ESTIMATOR<br>
1779: A MODIFIED LAPLACIAN FILTER WITH INTENSITY CORRECTION TECHNIQUE FOR IMAGE RESOLUTION ENHANCEMENT<br>
1780: USER-ASSISTED IMAGE CLASSIFICATION ON PERSONAL PHOTO COLLECTIONS<br>
1782: A COMPARISON OF THREE 3-D FACIAL RECONSTRUCTION APPROACHES<br>
1783: PERCEPTUALLY ENHANCED BIT-PLANE CODING FOR SCALABLE AUDIO<br>
1784: A ROBUST METHOD FOR TV LOGO TRACKING IN VIDEO STREAMS<br>
1792: AN EFFICIENT MEMORY CONSTRUCTION SCHEME FOR AN ARBITRARY SIDE GROWING HUFFMAN TABLE<br>
1795: NON-BANDLIMITED RESAMPLING OF IMAGES<br>
1796: A STUDY ON SPATIAL SCALABLE CODING USING VECTOR REPRESENTATION<br>
1798: WEB IMAGE MINING BASED ON MODELING CONCEPT-SENSITIVE SALIENT REGIONS<br>
1799: IMPROVEMENTS ON RATE-DISTORTION PERFORMANCE OF H.264 RATE CONTROL IN LOW BIT RATE VIDEO CODING<br>
1802: TOWARDS ROBUST INTUITIVE VISION-BASED USER INTERFACES<br>
1803: PASS: PEER-AWARE SILENCE SUPPRESSION FOR INTERNET VOICE CONFERENCES<br>
1804: THE INTERACTIVE COOKING SUPPORT SYSTEM IN MIXED REALITY ENVIRONMENT<br>
1806: THE WATERMARKING FOR 3D CAD DRAWING USING LINE, ARC, 3DFACE COMPONENTS<br>
1808: AUTOMATIC GEOMETRIC AND PHOTOMETRIC CALIBRATION FOR TILING MULTIPLE PROJECTORS WITH A PAN-TILT-ZOOM CAMERA<br>
1811: A FAST DOWNSIZING VIDEO TRANSCODER FOR H.264/AVC WITH R-D OPTIMAL MODE DECISION<br>
1816: RAIN REMOVAL IN VIDEO BY COMBINING TEMPORAL AND CHROMATIC PROPERTIES<br>
1817: AUTOMATIC COUNTING OF INTERACTING PEOPLE BY USING A SINGLE UNCALIBRATED CAMERA<br>
1818: POSTER IMAGE MATCHING FROM COLOR SCHEME AND LAYOUT INFORMATION<br>
1821: EFFICIENT MOTION ESTIMATION USING SORTING-BASED PARTIAL DISTORTION SEARCH <br>
1823: AN EFFICIENT NUMERIC INDEXING TECHNIQUE FOR MUSIC RETRIEVAL SYSTEM<br>
1824: A NEW JOINT SOURCE-CHANNEL MODELING APPROACH FOR ADAPTIVE FEC CODE RATE DECISION<br>
1832: NEW AREA MATRIX-BASED AFFINE-INVARIANT SHAPE FEATURES AND SIMILARITY METRICS<br>
1833: MULTIPLIERLESS APPROXIMATION OF FAST DCT ALGORITHMS<br>
1834: INQUIRING OF THE SIGHTS FROM THE WEB VIA CAMERA MOBILES<br>
1839: A CONTENT-AWARE STREAM AUTHENTICATION SCHEME OPTIMIZED FOR DISTORTION AND OVERHEAD<br>
1840: AN EFFECTIVE METHOD FOR TRAINING AND COMBINING SVMS FOR MULTIPLE FEATURES CLASSIFICATION<br>
1841: DETECTION AND RESTORATION OF OCCLUSIONS FOR 3D FACE RECOGNITION<br>
1843: SEMANTIC 3D FACE MESH SIMPLIFICATION FOR TRANSMISSION AND VISUALIZATION<br>
1854: OBJECT TRACKING IN COMPRESSED VIDEO WITH CONFIDENCE MEASURES<br>
1855: INTEGRATION OF BACKGROUND MODELING AND OBJECT TRACKING<br>
1856: A FAST MODE SELECTION ALGORITHM IN H.264 VIDEO CODING<br>
1858: DESIGN OF AUDIO/VIDEO DECODER FOR THE T-DMB RECEIVER<br>
1861: DIRECTIONAL DISCRETE COSINE TRANSFORMS FOR IMAGE CODING<br>
1863: A PRIORITY-BASED ADAPTIVE SCHEME FOR WIRELESS MULTIMEDIA DELIVERY<br>
1867: A BEHAVIOURAL APPROACH TO PERSON RECOGNITION<br>
1868: USING IMPLICIT RELEVANCE FEEDBACK TO ADVANCE IMAGE SEARCH<br>
1877: A MOTION VECTOR RECOVERY ALGORITHM FOR TEMPORAL ERROR CONCEALMENT USING OPTICAL FLOW IN H.264 VIDEO CODING<br>
1878: REVERSIBLE IMAGE AUTHENTICATION BASED ON WATERMARKING<br>
1880: EFFECTIVE ERROR CONCEALMENT ALGORITHM BY BOUNDARY INFORMATION FOR H.264 VIDEO DECODER<br>
1881: LOW POWER ENTROPY CODING HARDWARE DESIGN FOR H.264/AVC BASELINE PROFILE ENCODER<br>
1882: ONLINE MINING OF RECENT MUSIC QUERY STREAMS<br>
1886: AN AUTOMATIC CLASSIFICATION SYSTEM APPLIED IN MEDICAL IMAGES<br>
1891: A NEW IMAGE CORRECTION METHOD FOR MULTIVIEW VIDEO SYSTEM<br>
1892: SCALABLE IMAGE RETRIEVAL FROM DISTRIBUTED IMAGES DATABASE<br>
1893: MODIFIED WINNER UPDATE WITH ADAPTIVE BLOCK PARTITION FOR FAST MOTION ESTIMATION<br>
1896: STEGANALYSIS BASED ON MARKOV MODEL OF THRESHOLDED PREDICTION-ERROR IMAGE<br>
1898: A RANK BASED METRIC OF ANCHOR MODELS FOR SPEAKER VERIFICATION<br>
1904: A MUTUAL INFORMATION BASED FACE CLUSTERING ALGORITHM FOR MOVIES<br>
1905: POSTFILTERING FOR SUPPRESSION OF RESIDUAL ECHO FROM VOCODER DISTORTION IN PACKET-BASED TELEPHONY<br>
1908: AN NEW COEFFICIENTS TRANSFORM MATRIX FOR THE TRANSFORM DOMAIN MPEG-2 TO H.264/AVC TRANSCODING<br>
1912: SEAMLESS SWITCHING IN MULTI-RATE VIDEO STREAMING SYSTEMS: A WAVELET-BASED SCHEME VERSUS THE SP-FRAME SCHEME<br>
1916: BRINGING THE WIKI COLLABORATION MODEL TO THE TABLETOP WORLD<br>
1917: OFF-LINE MOTION DESCRIPTION FOR FAST VIDEO STREAM GENERATION IN MPEG-4 AVC/H.264<br>
1921: IDENTIFICATION AND DETECTION OF THE SAME SCENE BASED ON FLASHLIGHT PATTERNS<br>
1924: CELL BROADBAND ENGINE BASED REALTIME WAVELET DECOMPOSITION FOR HDTV VIDEO IMAGE AND BEYOND<br>
1926: STREAM CIPHER WITH DRIFT CONTROL FOR CONDITIONAL ACCESS TO H.264/AVC VIDEO<br>
1928: AN OPTIMAL NON-UNIFORM SCALAR QUANTIZER FOR DISTRIBUTED VIDEO CODING<br>
1930: SEAMLESS MULTIMEDIA TRANSMISSION DURING FAST HANDOVER IN MOBILE IPV6 ENVIRONMENT<br>
1934: A CONTEXT-BASED ERROR DETECTION STRATEGY INTO H.264/AVC CABAC<br>
1939: AUTOMATIC SPEAKER SEGMENTATION USING MULTIPLE FEATURES AND DISTANCE MEASURES: A COMPARISON OF THREE APPROACHES<br>
1940: AN INTELLIGENT GUIDING BULLETIN BOARD SYSTEM WITH REAL-TIME VISION AND MULTI-KEYWORD SPOTTING MULTIMEDIA HUMAN-COMPUTER INTERACTION<br>
1941: ADVANCED WIRELESS MULTIUSER VIDEO STREAMING USING THE SCALABLE VIDEO CODING EXTENSIONS OF H.264/MPEG-4 AVC<br>
1942: USING DECISION-TREE TO AUTOMATICALLY CONSTRUCT LEARNED-HEURISTICS FOR EVENTS CLASSIFICATION IN SPORTS VIDEO<br>
1944: ON THE USE OF TIME-FREQUENCY REPRESENTATION IN MULTICOMPONENT SIGNAL SEPARATION<br>
1947: MATCHING FACES WITH TEXTUAL CUES IN SOCCER VIDEOS<br>
1948: A HANDOVER APPROACH TO DVB-H SERVICES<br>
1956: BROADCAST VIDEO PROGRAM SUMMARIZATION USING FACE TRACKS<br>
1959: 3D FACE IDENTIFICATION BASED ON ARRANGEMENT OF SALIENT WRINKLES<br>
1960: A DIAGNOSTIC FRAMEWORK FOR PEER-TO-PEER STREAMING<br>
1968: A SYSTEM FOR AUTOMATIC JUDGMENT OF OFFSIDES IN SOCCER GAMES<br>
1979: GENERATING EXPRESSIVE SUMMARIES FOR SPEECH AND MUSICAL AUDIO USING SELF-SIMILARITY CLUES<br>
1980: TOWARD INTELLIGENT USE OF SEMANTIC INFORMATION ON SUBSPACE DISCOVERY FOR IMAGE RETRIEVAL<br>
1982: ON RESAMPLING DETECTION AND ITS APPLICATION TO DETECT IMAGE TAMPERING<br>
1983: SELF-SUPERVISED LEARNING FOR ROBUST VIDEO INDEXING<br>
1984: A NEW STUDY ON DISTANCE METRICS AS SIMILARITY MEASUREMENT<br>
1988: FACIAL ACTION UNITS AND EMOTIONS<br>
1989: VOICE ACTIVITY DETECTION WITH GENERALIZED GAMMA DISTRIBUTION<br>
1992: COMPUTING A MULTIMEDIA REPRESENTATION FOR DOCUMENTS GIVEN TIME AND DISPLAY CONSTRAINTS<br>
1993: COMBINING TEXTUAL AND VISUAL ONTOLOGIES TO SOLVE MEDICAL MULTIMODAL QUERIES<br>
1995: CONFRONTING THE SYNCHRONIZATION PROBLEM OF SEMANTIC REGION UNDER GEOMETRIC ATTACKS<br>
2004: A ROBUST IMAGE WATERMARKING SCHEME BASED ON THE ALPHA-BETA SPACE<br>
2008: AN ARCHITECTURE DESIGN OF THRESHOLD-BASED BEST-BASIS ALGORITHM<br>
2012: EXPERIENCES WITH HIGH DEFINITION INTERACTIVE VIDEO CONFERENCING<br>
2015: VIRTUAL DENTAL PATIENT: A SYSTEM FOR VIRTUAL TEETH DRILLING<br>
2020: DYNAMIC RATE CONTROL FOR JPEG 2000 TRANSCODING<br>
2021: SUBSTREAM ALLOCATION IN LAYERED P2P STREAMING<br>
2022: AN ANALYTICAL STUDY OF STREAM TAPPING PROTOCOLS<br>
2023: ADAPTATION SCENARIOS FOR NEW MEDIA ARTWORKS<br>
2024: GPUCV: AN FRAMEWORK FOR IMAGE PROCESSING ACCELERATION WITH GRAPHICS PROCESSORS<br>
2031: A NOVEL DESIGN TO SUPPORT INTERNET STREAMING VIA WEB SERVERS<br>
2033: EFFICIENT WIRELESS MULTICAST PROTOCOL WITH ORTHOGONAL CTS MODULATION SUPPORTING VIDEO CONFERENCING<br>
2034: ANALYSIS OF HIERARCHICAL B PICTURES AND MCTF<br>
2036: ACHIEVING SIMULTANEOUS DISTRIBUTION CONTROL AND PRIVACY PROTECTION FOR INTERNET MEDIA DELIVERY<br>
2038: HYBRID TRAITOR TRACING<br>
2041: A FINGERPRINTING SYSTEM FOR MUSICAL CONTENT<br>
2042: MUSICAL SIGNAL TYPE DISCRIMINATION BASED ON LARGE OPEN FEATURE SETS<br>
2043: ROBUST DISTRIBUTED MULTI-POINT VIDEO CONFERENCING OVER ERROR-PRONE CHANNELS<br>
2044: IMAGE REPLICA DETECTION USING R-TREES AND LINEAR DISCRIMINANT ANALYSIS<br>
2045: VIDEO TRANSCODING FOR PACKET LOSS RESILIENCE BASED ON THE MULTIPLE DESCRIPTIONS<br>
2050: MOVIES MADE THROUGH THE EYES OF A MOBILE USER WITH A GAZE-ALIGNED CAMERA<br>
2053: INTERNET TRAFFIC CLASSIFICATION FOR SCALABLE QOS PROVISION<br>
2056: FAST ADAPTATION DECISION TAKING FOR CROSS-MODAL MULTIMEDIA CONTENT ADAPTATION<br>
2057: EMOTIONAL SPEECH SYNTHESIS USING SUBSPACE CONSTRAINTS IN PROSODY<br>
2058: EFFICIENT RECOGNITION OF AUTHENTIC DYNAMIC FACIAL EXPRESSIONS ON THE FEEDTUM DATABASE<br>
2059: PARTIAL LDA VS PARTIAL PCA<br>
2062: SCCS: A SCALABLE CLUSTERED CAMERA SYSTEM FOR MULTIPLE OBJECT TRACKING COMMUNICATING VIA MESSAGE PASSING INTERFACE<br>
2067: FACE RECOGNITION USING 3D SUMMATION INVARIANT FEATURES<br>
2070: AUTOMATIC EXTRACTION OF GEOMETRIC LIP FEATURES WITH APPLICATION TO MULTI-MODAL SPEAKER IDENTIFICATION<br>
2074: DATA HIDING FOR SPEECH BANDWIDTH EXTENSION AND ITS HARDWARE IMPLEMENTATION<br>
2078: ADAPTIVE ERASURE RESILIENT CODING IN DISTRIBUTED STORAGE<br>
2081: RTP AND THE DATAGRAM CONGESTION CONTROL PROTOCOL<br>
2083: A FAST VIDEO MOTION ESTIMATION ALGORITHM FOR THE H.264 STANDARD<br>
2085: MULTIPOINT MEASURING SYSTEM FOR VIDEO AND SOUND - 100-CAMERA AND MICROPHONE SYSTEM -<br>
2086: VISUAL EVENT DETECTION USING MULTI-DIMENSIONAL CONCEPT DYNAMICS<br>
2087: PERSON TRACKING IN SMART ROOMS USING DYNAMIC PROGRAMMING AND ADAPTIVE SUBSPACE LEARNING<br>
2089: ANALYSIS AND EVALUATION OF THE SKYPE AND GOOGLE-TALK VOIP SYSTEMS<br>
2090: VIDEO TRANSPORT OVER MULTI HOP DIRECTIONAL WIRELESS NETWORKS<br>
2091: HIERARCHICAL GENRE CLASSIFICATION FOR LARGE MUSIC COLLECTIONS<br>
2095: SPREAD-SPECTRUM SUBSTITUTION WATERMARKING GAME<br>
2096: AN OPTIMAL AND STATISTICALLY ROBUST CORRELATION TECHNIQUE FOR BLOCK BASED MOTION ESTIMATION<br>
2097: A NEW APPROACH FOR FEATURES TEXTURE EXTRACTION: APPLICATION FOR TEXT LOCALIZATION IN VIDEO IMAGES<br>
2099: A HIERARCHICAL APPROACH FOR MUSIC CHORD MODELING BASED ON THE ANALYSIS OF TONAL CHARACTERISTICS<br>
2102: ADAPTIVE MCTF BASED ON CORRELATION NOISE MODEL FOR SNR SCALABLE VIDEO CODING<br>
2105: EXPLORING AUTOMATIC QUERY REFINEMENT FOR TEXT-BASED VIDEO RETRIEVAL<br>
2106: AN EFFECTIVE MODE DECISION SCHEME IN MACROBLOCK-BASED PFGS<br>
2115: IMAGE VECTOR QUANTIZATION INDICES RECOVERY USING LAGRANGE INTERPOLATION<br>
2116: DETECTING IMAGE SPLICING USING GEOMETRY INVARIANTS AND CAMERA CHARACTERISTICS CONSISTENCY<br>
2118: TV VIEWING INTERVAL ESTIMATION FOR PERSONAL PREFERENCE ACQUISITION<br>
2122: SYNDROME-BASED LIGHT-WEIGHT VIDEO CODING FOR MOBILE WIRELESS APPLICATION<br>
2126: MULTICAST OF REAL TIME MULTI-VIEW VIDEO<br>
2128: AN INNOVATIVE PIXEL SCORING METHOD FOR WATERMARKING OF BINARY DOCUMENT IMAGES<br>
2129: DIRECTING ATTENTION IN ONLINE AGGREGATE SENSOR STREAMS VIA AUDITORY BLIND VALUE ASSIGNMENT<br>
2130: EFFICIENT PARTIAL SPECTRUM RECONSTRUCTION USING AN ASYMMETRIC PQMF ALGORITHM FOR MPEG-CODED STEREO AUDIO<br>
2134: SUMMARIZATION OF SPONTANEOUS CONVERSATIONS WITH RICH FEATURES<br>
2135: JOINT RATE-DISTORTION-COMPLEXITY OPTIMIZATION FOR H.264 MOTION SEARCH<br>
2137: GPU-BASED OCEAN RENDERING<br>
2141: A NEW QUANTIZATION FOR RATE CONTROL WITH FRAME VARIATION CONSIDERATION<br>
2143: PERMUTATION-BASED LOW-COMPLEXITY ALTERNATE CODING IN MULTI-VIEW H.264/AVC<br>
2144: JOINT ADAPTIVE INTRA REFRESHMENT AND UNEQUALLY ERROR PROTECTION ALGORITHMS FOR ROBUST TRANSMISSION OF H.264/AVC VIDEO<br>
2152: DESIGNING INTERACTIONS IN EVENT-BASED UNIFIED MANAGEMENT OF PERSONAL MULTIMEDIA INFORMATION<br>
2156: MULTI-ISSUE MULTI-THREADED STREAM PROCESSOR<br>
2161: DISCOVR: DISTRIBUTED COLLABORATIVE VIDEO RECORDER<br>
2166: BANDWIDTH ESTIMATION IN WIRELESS LANS FOR MULTIMEDIA STREAMING SERVICES<br>
2172: CAMERA MOTION DETECTION USING VIDEO MOSAICING<br>
2173: ACOUSTIC ECHO CANCELLATION IN A CHANNEL WITH RAPIDLY VARYING GAIN<br>
2177: ROBUST VIDEO TRANSMISSION OVER MIMO-OFDM SYSTEM USING MDC AND SPACE TIME CODES<br>
2179: DATA EMBEDDING IN MPEG-1/AUDIO LAYER II COMPRESSED DOMAIN USING SIDE INFORMATION<br>
2187: A VIDEO SCRAMBLING SCHEME APPLICABLE TO LOCAL REGION WITHOUT DATA EXPANSION<br>
2189: OPTIMAL ERROR PROTECTION OF PROGRESSIVELY COMPRESSED 3D MESHES<br>
2190: PROVISIONING CONTEXT-AWARE ADVERTISEMENTS TO WIRELESS MOBILE USERS<br>
2191: MOVIE-BASED MULTIMEDIA MATRIX LIBRARY<br>
2192: SVM-BASED SHOT BOUNDARY DETECTION WITH A NOVEL FEATURE<br>
2193: EFFICIENT SPEAKER DETECTION VIA TARGET DEPENDENT DATA REDUCTION<br>
2196: PEER-TO-PEER ASYNCHRONOUS VIDEO STREAMING USING SKIP LIST<br>
2197: H.263 VIDEO CODEC PERFORMANCE WITH A FAST 8X8 INTEGER IDCT<br>
2200: SEMANTIC MULTIMEDIA RETRIEVAL USING LEXICAL QUERY EXPANSION AND MODEL-BASED RERANKING<br>
2203: POWER-SCALABLE ALGORITHM AND RECONFIGURABLE MACRO-BLOCK PIPELINING ARCHITECTURE OF H.264 ENCODER FOR MOBILE APPLICATION<br>
2204: SHAPE-BASED VISUAL QUERY REWRITING<br>
2205: SPECIAL EFFECTS IN FILM/VIDEO MAKING: A NEW MEDIA INITIATIVE PROJECT<br>
2207: SEMANTIC LABELING OF MULTIMEDIA CONTENT CLUSTERS<br>
2209: A GLOBAL CORRESPONDENCE FOR SCALE INVARIANT MATCHING USING MUTUAL INFORMATION AND THE GRAPH SEARCH<br>
2210: PATTERN MINING IN VISUAL CONCEPT STREAMS<br>
2213: DIBR-BASED 3D VIDEOS USING NON VIDEO RATE RANGE IMAGE STREAM<br>
2214: VIDEO NEWS SHOT LABELING REFINEMENT VIA SHOT RHYTHM MODELS<br>
2217: VISUAL FEATURE SPACE ANALYSIS FOR UNSUPERVISED EFFECTIVENESS ESTIMATION AND FEATURE ENGINEERING<br>
2219: ON PARALLELIZATION OF A VIDEO MINING SYSTEM<br>
2220: THE DIFFERENCES BETWEEN TOED-IN CAMERA CONFIGURATIONS AND PARALLEL CAMERA CONFIGURATIONS IN SHOOTING STEREOSCOPIC IMAGES<br>
2222: RECEIVER-BASED OPTIMIZATION FOR VIDEO DELIVERY OVER WIRELESS LINKS<br>
2223: OPTIMAL REQUANTIZATION-BASED RATE ADAPTATION FOR H.264<br>
2227: EFFICIENT SEARCH IN P2P-BASED VIDEO-ON-DEMAND STREAMING SERVICE<br>
2229: VIDEO ANNOTATION BY ACTIVE LEARNING AND SEMI-SUPERVISED ENSEMBLING<br>
2231: LOW LATENCY VIDEO STREAMING OVER PEER-TO-PEER NETWORKS<br>
2232: A FLEXIBLE 3D TV SYSTEM FOR DIFFERENT MULTI-BASELINE GEOMETRIES<br>
2233: EMBEDDED CONVOLUTIONAL FACE FINDER<br>
2234: DISTRIBUTED MEDIA RATE ALLOCATION IN OVERLAY NETWORKS<br>
2235: PERSONALIZED SEARCH OF EDUCATIONAL CONTENT BASED ON MULTIPLE ONTOLOGIES<br>
2236: RIPPLE-STREAM: SAFEGUARDING P2P STREAMING AGAINST DOS ATTACKS<br>
2237: A FAST INTRA MODE DECISION ALGORITHM FOR AVS TO H.264 TRANSCODING<br>
2238: INVOLVING CLIENTS IN THE DISTRIBUTION OF VIDEOS ON DEMAND<br>
2239: INTERACTIONS AND INTEGRATIONS OF MULTIPLE SENSORY CHANNELS IN HUMAN BRAIN<br>
2240: PREFILTER CONTROL SCHEME FOR LOW BITRATE TV DISTRIBUTION<br>
2241: CROSS-LAYER DESIGN OF SOURCE RATE CONTROL AND QOS-AWARE CONGESTION CONTROL FOR WIRELESS VIDEO STREAMING<br>
2242: A REAL TIME INTERACTIVE DYNAMIC LIGHT FIELD TRANSMISSION SYSTEM<br>
2243: SIM: SCALABLE ISLAND MULTICAST FOR PEER-TO-PEER MEDIA STREAMING<br>
2244: A ROADMAP FOR AUTOSTEREOSCOPIC MULTI-VIEWER DOMESTIC TV DISPLAYS<br>
2248: HUMAN FACTORS FOR STEREOSCOPIC IMAGES<br>
2249: OFFERING DIFFERENTIATED SERVICES IN PEER-TO-PEER MULTIMEDIA MULTICAST<br>
2251: END-TO-END STEREOSCOPIC VIDEO STREAMING SYSTEM<br>
2253: AUTOMATIC MEDICAL IMAGE ANNOTATION AND SEMANTIC RETRIEVAL<br>
2256: COSMOS: PEER-TO-PEER COLLABORATIVE STREAMING AMONG MOBILES<br>
2258: A SURVEY OF PEER-TO-PEER NETWORK FOR MULTIMEDIA CONTENT<br>
2260: OPTIMIZING ALGORITHMS FOR REGION-OF-INTEREST VIDEO COMPRESSION, WITH APPLICATION TO MOBILE TELEHEALTH<br>
2261: A CROSS-LAYERED PEER-TO-PEER ARCHITECTURE FOR WIRELESS MOBILE NETWORKS<br>
2262: COOPERATIVE MULTITHREADING: AN OPEN SCALABLE AND CONFIGURABLE PROCESSOR FOR EMBEDDED MULTIMEDIA APPLICATIONS<br>
2264: SCALABILITY OF MULTIMEDIA APPLICATIONS ON NEXT-GENERATION PROCESSORS<br>
2265: TOWARDS THE APPLICATION OF A HANDWRITING INTERFACE FOR MATHEMATICS LEARNING<br>
2267: VIDEO ANALYSIS AND COMPRESSION ON THE STI CELL BROADBAND ENGINE PROCESSOR<br>
2268: EFFICIENT VIDEO DISSEMINATION IN STRUCTURED HYBRID P2P NETWORKS<br>
2269: APPLICATIONS OF AUTOSTEREOSCOPIC DISPLAYS IN OPTHALMOLOGIC STUDIES<br>
2270: SCALABLE MULTI-VIEW VIDEO CODING FOR INTERACTIVE 3DTV<br>
2273: OVERVIEW OF LOW-COMPLEXITY VIDEO TRANSCODING FROM H.263 TO H.264<br>
2274: PERSONAL MEDIA ALERT SYSTEMS: PERSONALIZATION AND DISSEMINATION OF BROADCAST CONTENT WITH A P2P MICROPAYMENT SCHEME <br>
2275: 3D-TV CONTENT GENERATION: 2D TO 3D IMAGE AND VIDEO CONVERSION<br>
2277: VIDEO TEXTURE AND MOTION BASED MODELING OF RATE VARIABILITY-DISTORTION (VD) CURVES OF I, P, AND B FRAMES<br>
2278: RD-OPTIMIZATION FOR MPEG-2 TO H.264 TRANSCODING<br>
2279: ON THE DESIGN OF PREFETCHING STRATEGIES IN A PEER-DRIVEN VIDEO ON-DEMAND SYSTEM<br>
2280: ON THE POTENTIAL OF INCORPORATING KNOWLEDGE OF HUMAN VISUAL ATTENTION INTO CBIR SYSTEMS<br>
2281: CROSS LAYER ADAPTATION FOR H.264 VIDEO MULTICASTING OVER WIRELESS LAN<br>
2282: PATH-DIVERSITY OVERLAY RETRANSMISSION ARCHITECTURE FOR RELIABLE MULTICAST<br>
2283: AN UNBALANCED MULTIPLE DESCRIPTION CODING SCHEME FOR VIDEO TRANSMISSION OVER WIRELESS AD HOC NETWORKS<br>
2284: MOTION AND MODE MAPPING FOR MPEG-2 TO H.264/AVC TRANSCODING<br>
2286: PAC DSP CORE AND APPLICATION PROCESSORS<br>
2287: PERCEPTUAL SHARPNESS METRIC (PSM) FOR COMPRESSED VIDEO<br>
2288: INFLUENCE OF GRAPH PROPERTIES OF PEER-TO-PEER TOPOLOGIES ON VIDEO STREAMING WITH NETWORK EMBEDDED FEC<br>
2290: A SIMPLE AND ACCURATE COLOR FACE DETECTION ALGORITHM IN COMPLEX BACKGROUND<br>
2291: A CAPTCHA BASED ON THE HUMAN VISUAL SYSTEMS MASKING CHARACTERISTICS<br>
2292: PHOTOREALISTIC ATTENTION-BASED GAZE ANIMATION<br>
2293: AN EFFICIENT ALGORITHM FOR VC-1 TO H.264 VIDEO TRANSCODING IN PROGRESSIVE COMPRESSION<br>
2295: CHALLENGES AND OPPORTUNITIES IN VIDEO CODING FOR 3D TV<br>
2296: EFFICIENT PACKET STRIPING FOR MEDIA STREAMING OVER MULTIPLE BURST-LOSS CHANNELS WITH RANDOM DELAYS<br>
2297: AN INERACTIVE REGION-BASED IMAGE CLUSTERING AND RETRIEVAL PLATFORM<br>
2300: INTERACTIVE CONTENT-AWARE MUSIC BROWSING USING THE RADIO DRUM<br>
2301: ANALYSIS OF MULTI-USER CONGESTION CONTROL FOR VIDEO STREAMING OVER WIRELESS NETWORKS<br>
2302: CARRIAGE OF 3D AUDIO-VISUAL SERVICES BY T-DMB<br>
2303: A VIOLIN MUSIC TRANSCRIBER FOR PERSONALIZED LEARNING<br>
2306: NEAR-FUTURE STREAMING FRAMEWORK FOR 3D-TV APPLICATIONS<br>
2307: GAME-THEORETIC PARADIGM FOR RESOURCE MANAGEMENT IN SPECTRUM AGILE WIRELESS NETWORKS <br>
2308: MPEG-4 TO H.264 TRANSCODING USING MACROBLOCK STATISTICS<br>
2309: LABEL DISAMBIGUATION AND SEQUENCE MODELING FOR IDENTIFYING HUMAN ACTIVITIES FROM WEARABLE PHYSIOLOGICAL SENSORS<br>
2311: DESIGN AND VERIFICATION OF COMMUNICATION PROTOCOLS FOR PEER-TO-PEER MULTIMEDIA SYSTEMS<br>
2312: USING P2P NETWORKS FOR ERROR RECOVERY IN MBMS APPLICATIONS<br>
2315: CROSS-LAYER CONGESTION CONTROL, SCHEDULING AND POWER CONTROL DESIGN IN MULTIHOP NETWORKS WITH RANDOM ACCESS<br>
2316: SPECIALIZED VIDEO AND PHYSIOLOGICAL DATA CODING SYSTEM FOR REMOTE MONITORING<br>
2319: ADAPTIVE MULTIMEDIA FLOW REGULATION AND DELAY ANALYSIS FOR END-HOSTS IN P2P NETWORKS<br>
2320: SIGN LANGUAGE RECOGNITION FROM HOMOGRAPHY
</p>

<div style="height: 1em;"></div>
<!-- Begin Footer --></div></div>
<hr class="cleaner" />
<div id="FooterBlock">
  <p>&copy;2014 <a href="http://www.cmsworldwide.com/">Conference Management Services, Inc.</a> -||- email: <a href="mailto:webmaster@icme2006.org">webmaster@icme2006.org</a> -||- Last updated Tuesday, March 21, 2006</p>
</div>
  </body>
</html>
