<?php
include 'include.php';
echoStart();
?>

<h1>Paper Submission</h1>

<h2>Regular Papers</h2>
<ol>
  <li>Please read the <a href="crguide.php"><u><strong>Camera-Ready Submission Guidelines</strong></u></a> before proceeding.</li>
  <li>Camera-ready paper templates are available at <a href="crguide.php#crt"><strong><u>here</u></strong></a>.</li>
  <li>Electronic copyright forms are to be submitted to IEEE from the <a href="copyright.php"><u><strong>Copyright Submission</strong></u></a> page.</li>
  <li>Camera-ready submission must be in letter-sized PDF. The PDF must be IEEE Xplore compliant. This can be verified by the PDF eXpress system at <a href="http://www.pdf-express.org/" ,="" target="_blank"><u><strong>http://www.pdf-express.org</strong></u></a>. Please use &ldquo;<font color="#770000"><strong>icme11x</strong></font>&rdquo; as the Conference ID to log on.</li>
  <li>Make sure your filename is in the form of &ldquo;<font color="#770000"><strong>paper_id.pdf</strong></font>&rdquo; before submission.</span></li>
  <li><strong>Camera-ready paper</strong> submission must be in PDF format verified/generated by the PDF eXpress system and submitted via the following link:<br /><br />
  <a href="https://cmt.research.microsoft.com/ICME2011/" target="_blank"><s><u><strong>Upload Submission</strong></u></s></a></li>
</ol>
<br />

<h2>Industrial/Application Short Papers</h2>
<ol>
  <li>Please read the <a href="crguide.php"><u><strong>Camera-Ready Submission Guidelines</strong></u></a> before proceeding.</li>
  <li>Camera-ready paper templates are available at <a href="crguide.php#crt"><strong><u>here</u></strong></a>.</li>
  <li>Electronic copyright forms are to be submitted to IEEE from the <a href="copyright.php"><u><strong>Copyright Submission</strong></u></a> page.</li>
  <li>Camera-ready submission must be in letter-sized PDF. The PDF must be IEEE Xplore compliant. This can be verified by the PDF eXpress system at <a href="http://www.pdf-express.org/" ,="" target="_blank"><u><strong>http://www.pdf-express.org</strong></u></a>. Please use &ldquo;<font color="#770000"><strong>icme11x</strong></font>&rdquo; as the Conference ID to log on. <font color="#770000"><strong>IEEE PDF eXpress is now operating.</strong></font></li>
  <li>Make sure your filename is in the form of &ldquo;<font color="#770000"><strong>paper_id.pdf</strong></font>&rdquo; before submission.</span></li>
  <li><strong>Camera-ready paper</strong> submission must be in PDF format verified/generated by the PDF eXpress system and submitted via the following link:<br /><br />
  <a href="https://cmt.research.microsoft.com/ICME2011/" target="_blank"><u><strong>Upload Submission</strong></u></a></li>
</ol>
<br />

<h2>Demos</h2>
<ol>
  <li>Please read the <a href="crguide.php"><u><strong>Camera-Ready Submission Guidelines</strong></u></a> before proceeding.</li>
  <li>Camera-ready paper templates are available at <a href="crguide.php#crt"><strong><u>here</u></strong></a>.</li>
  <li>Electronic copyright forms are to be submitted to IEEE from the <a href="copyright.php"><u><strong>Copyright Submission</strong></u></a> page.</li>
  <li>Camera-ready submission must be in letter-sized PDF. The PDF must be IEEE Xplore compliant. This can be verified by the PDF eXpress system at <a href="http://www.pdf-express.org/" ,="" target="_blank"><u><strong>http://www.pdf-express.org</strong></u></a>. Please use &ldquo;<font color="#770000"><strong>icme11x</strong></font>&rdquo; as the Conference ID to log on. <font color="#770000"><strong>IEEE PDF eXpress is now operating.</strong></font></li>
  <li>Make sure your filename is in the form of &ldquo;<font color="#770000"><strong>paper_id.pdf</strong></font>&rdquo; before submission.</span></li>
  <li><strong>Camera-ready paper</strong> submission must be in PDF format verified/generated by the PDF eXpress system and submitted via the following link:<br />
    <br />
    <a href="https://cmt.research.microsoft.com/ICME2011/" target="_blank"><u><strong>Upload Submission</strong></u></a></li>
</ol>
<br />

<h2>Workshop Papers</h2>
<ol>
  <li>Please read the <a href="crguide.php"><u><strong>Camera-Ready Submission Guidelines</strong></u></a> before proceeding.</li>
  <li>Camera-ready paper templates are available at <a href="crguide.php#crt"><strong><u>here</u></strong></a>.</li>
  <li>Electronic copyright forms are to be submitted to IEEE from the <a href="copyright.php"><u><strong>Copyright Submission</strong></u></a> page.</li>
  <li>Camera-ready submission must be in letter-sized PDF. The PDF must be IEEE Xplore compliant. This can be verified by the PDF eXpress system at <a href="http://www.pdf-express.org/" ,="" target="_blank"><u><strong>http://www.pdf-express.org</strong></u></a>. Please use &ldquo;<font color="#770000"><strong>icme11x</strong></font>&rdquo; as the Conference ID to log on. <font color="#770000"><strong>IEEE PDF eXpress is now operating.</strong></font></li>
  <li>Make sure your filename is in the form of &ldquo;<font color="#770000"><strong>Wxxx.pdf</strong></font>&rdquo; before submission, where is <font color="#770000"><strong>xxx</strong></font> your <font color="#770000"><strong>paper ID</strong></font>.</span></li>
  <li><strong>Camera-ready paper</strong> submission must be in PDF format verified/generated by the PDF eXpress system and submitted via the following link (<em>different from the regular paper and industrial paper submission site</em>):<br /><br />
  <a href="https://cmt.research.microsoft.com/ICMEW2011/" target="_blank"><u><strong>Upload Submission</strong></u></a><a href="https://cmt.research.microsoft.com/ICME2011/" target="_blank"></a></li>
</ol>

<?php
echoEnd();
?>